---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/tag.redis: glob:2.0.*
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: docker.io/matheusboy/redis:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
