apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: demo
spec:
  interval: 5m
  releaseName: redis
  targetNamespace: redis
  chart:
    spec:
      chart: ./charts/redis
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    image: docker.io/matheusboy/redis:2.0.9 # {"$imagepolicy": "flux-system:redis"}
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
