apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alpine
  namespace: alpine
spec:
  interval: 1m
  releaseName: alpine
  targetNamespace: alpine
  chart:
    spec:
      chart: ./charts/alpine
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    image: docker.io/matheusboy/alpine:1.0.1 # {"$imagepolicy": "flux-system:alpine"}
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
