apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-2
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis-2
    spec:
      containers:
      - name: redis-2
        image: docker.io/matheusboy/redis:2.0.2 # {"$imagepolicy": "flux-system:redis"}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
