---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
spec:
  interval: 5m
  releaseName: ghost
  targetNamespace: demo
  chart:
    spec:
      chart: ./charts/ghost/Chart.yaml
      sourceRef:
        kind: GitRepository
        name: releases-source
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: bitnami/ghost
      tag: 3.1.1-debian-9-r0
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: ClusterIP
    mariadb:
      master:
        persistence:
          enabled: false
