---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
spec:
  releaseName: ghost
  chart:
    spec:
      chart: ./charts/ghost
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: default
