---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: fluxV2
  url: ssh://git@github.com/MatheusBoy/flux-get-started

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
spec:
  releaseName: ghost
  chart:
    spec:
      chart: ./charts/ghost
      sourceRef:
        kind: GitRepository
        name: my-charts
        namespace: flux-system
