apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: flux-matheus
  username: kustomize-controller
  secretRef:
    name: discord-url
