apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis 
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis
    spec:
      - name: redis
        image: docker.io/matheusboy/redis:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
