nameOverride: ""
fullnameOverride: "alpine"

#########
## APLICATION
######

image:  docker.io/matheusboy/alpine:1.0.1 # {"$imagepolicy": "flux-system:alpine"}
imagePullPolicy: IfNotPresent
imagePullSecrets: []

#########
## SCHEDULING
######

resources: 
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

#########
## MONITORING
######

livenessProbe:
  path: "/"
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 10
  initialDelaySeconds: 20

readinessProbe:
  path: "/"
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 10
  initialDelaySeconds: 20

#########
## CONNECTIVITY
######

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: external-nginx
    # ingress.kubernetes.io/whitelist-source-range: 189.23.221.102/32
  hosts: []
    # - example.com.br
    # - example.org

  paths:
    '/': {}
    # '/other': {}

  tls: []
  # - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

#########
## SCALING / ROLLOUT
######

replicaCount: 1

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCpu: 70
  # custom:
  #   - type: Object
  #     object:
  #       metric:
  #         name: metric_name
  #       describedObject:
  #         kind: Deployment
  #         name: deployment_name
  #         apiVersion: /v1
  #       target:
  #         type: Value
  #         value: 200

pdb:
  maxUnavailable: 1
  # minAvailable: 1

rollingUpdate:
  maxSurge: 1
