apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: my-webhook-helmrelease-alert-info
  namespace: flux-system
spec:
  providerRef:
    name: my-webhook
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: demo
    - kind: HelmRelease
      name: '*'
      namespace: monitoring
    - kind: HelmRelease
      name: '*'
      namespace: sealed-secrets
