apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: discord-imageupdate-alert-info
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: ImageUpdateAutomation
      name: '*'
  exclusionList:
    - "no updates made"
    - "object not found"

