apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: my-webhook-repositories-alert-info
  namespace: flux-system
spec:
  providerRef:
    name: my-webhook
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    

