---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: tetris
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tetris
  policy:
    semver:
      range: 1.0.1

