name: PR-Generator
on:
  push:
    branches:
      - image-updates
    
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Image Update ${{ github.sha }}'
          base: master
          branch: image-updates
          delete-branch: true
          title: 'Image Update ${{ github.sha }}'
          labels: |
            Image Update
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          draft: false
