name: Pull Request on Branch Push
on:
  push:
    branches:
      - image-updates
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        base: master
        token: ${{ secrets.PAT }}
        branch: image-updates
        title: "Image Update - ${{ github.ref }}"
        body: |
          "Image from commit - ${{ github.sha }}"
        labels: "Image Update"
        assignees: ${{ github.actor }}
        reviewers: "MatheusBoy"